---
title: "My English activity"
author:
  - name: Senique Dorian
date: 11-14-2019
preview: image/library.jpg
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Activity :


- 1 october : reading of the english version of "Game of thrones" season 1
- 3 october : listening to 2 episodes of a podcast called "Science Vs" on spotify.
- 9 october : starting a Netflix serie called "Black miror" in english subtitle english (2 episodes)
- 12 october : still reading the Game of Thrones season 1 book 
- 13 october : watching 3 episodes of "How I met your mother" on netflix in english subtitle english
- 16 october : listening to an episode of an english podcast called "Myths and Legends" on spotify.
- 19 october : watching a "TedxTalk" on youtube about "How to get your brain to focus"
- 23 october : watching an half-season of "how I met your mother" on netflix
- 27 october : watching some Late show  from the channel "Jimmy Fallon" on Youtube 
- 1 november : reading a novel by Jack London called "The strenght of the strong"
-

